struct StringConstants {
	static let LABEL_IS_DEFAULT_ACCOUNT_DESCRIPTION = "LABEL_IS_DEFAULT_ACCOUNT_DESCRIPTION"
	static let LABEL_IS_DEFAULT_ACCOUNT = "LABEL_IS_DEFAULT_ACCOUNT"
	static let MENULABEL_ACCOUNT = "MENULABEL_ACCOUNT"
	static let LABEL_LOADING = "LABEL_LOADING"
	static let MENULABEL_CURRENCY_PICKER = "MENULABEL_CURRENCY_PICKER"
	static let MENULABEL_ADD_ACCOUNT = "MENULABEL_ADD_ACCOUNT"
	static let LABEL_DONE = "LABEL_DONE"
	static let LABEL_NAME = "LABEL_NAME"
	static let TEXTFIELD_NAME_PLACEHOLDER = "TEXTFIELD_NAME_PLACEHOLDER"
	static let LABEL_STARTING_BALANCE = "LABEL_STARTING_BALANCE"
	static let TEXTFIELD_STARTING_BALANCE_PLACEHOLDER = "TEXTFIELD_STARTING_BALANCE_PLACEHOLDER"
	static let LABEL_CURRENCY = "LABEL_CURRENCY"
}